"""empty message

Revision ID: 074536401448
Revises: 
Create Date: 2019-11-02 16:13:06.086773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074536401448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('test', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'test')
    # ### end Alembic commands ###
