"""empty message

Revision ID: 2a4088a6749e
Revises: 074536401448
Create Date: 2019-11-02 16:15:14.802736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a4088a6749e'
down_revision = '074536401448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('test', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
