"""empty message

Revision ID: 367ac3996526
Revises: 6979301bdebd
Create Date: 2019-11-04 17:41:18.393470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '367ac3996526'
down_revision = '6979301bdebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_path', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
