"""empty message

Revision ID: 641f4457c956
Revises: 78e814b772ae
Create Date: 2019-11-05 15:59:44.372029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '641f4457c956'
down_revision = '78e814b772ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_path', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
