"""empty message

Revision ID: 6979301bdebd
Revises: 2a4088a6749e
Create Date: 2019-11-04 17:14:37.874937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6979301bdebd'
down_revision = '2a4088a6749e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_path', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    # ### end Alembic commands ###
