"""empty message

Revision ID: 78e814b772ae
Revises: 367ac3996526
Create Date: 2019-11-04 17:41:40.584611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e814b772ae'
down_revision = '367ac3996526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_path', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    # ### end Alembic commands ###
