"""empty message

Revision ID: ff2a9109b9a5
Revises: 641f4457c956
Create Date: 2019-11-05 16:00:03.592881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2a9109b9a5'
down_revision = '641f4457c956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_path', sa.String(length=256), server_default='img/7dc3c78d-edf1-4827-b6d4-9043638f8024.jpg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    # ### end Alembic commands ###
